#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# update and install HAProxy
sudo apt-get update -y
apt-get -y install haproxy

# configuration
server_config=\
"
frontend  client
        bind *:80
        mode http
        default_backend serverAll
backend serverAll
        mode http
        balance roundrobin
        server 70986-web-01 54.157.170.75:80
        server 70986-web-02 52.3.251.44:80
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
